declare module '@editorjs/inline-code';
declare module '@editorjs/marker';
declare module '@editorjs/list';
declare module '@editorjs/image';
declare module '@editorjs/header';
declare module '@editorjs/paragraph';
declare module '@editorjs/embed';
declare module '@editorjs/code';
declare module '@editorjs/quote';